# Generated by Django 2.2 on 2020-03-07 14:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('societies', '0003_owners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
    ]
