# Generated by Django 2.2 on 2020-03-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('societies', '0004_auto_20200307_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenancebill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('paid', models.CharField(default='no', max_length=3)),
                ('for_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societies.SocietyDetail')),
            ],
        ),
    ]
