# Generated by Django 2.2 on 2020-03-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0005_maintenancebill'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='voters',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='forum',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
